[kubemonkey]
dry_run = true                           # Terminations are only logged
run_hour = 11:40                           # Run scheduling at 8am on weekdays
start_hour = 11:45                         # Don't schedule any pod deaths before 10am
end_hour = 13                            # Don't schedule any pod deaths after 4pm
blacklisted_namespaces = ["kube-system", "testkube"] # Critical apps live here
time_zone = "America/New_York"   

run_hour = 11:40
      start_hour = 11:45
      end_hour = 13
      blacklisted_namespaces = ["kube-system", "testkube"]